@url = http://127.0.0.1/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA1NzE3M2VkOWY5YTJjMWY3NDQ5YzIiLCJuYW1lIjoidG9yY2hpem0iLCJlbWFpbCI6ImlzbWFpbHB2bzE1MzVAZ21haWwuY29tIiwiaWF0IjoxNjQ1NjM4ODUwfQ.h4Qst99Uh1soPFPvL8qsCDVojswtz3-8kB-_hVACKvA

###

POST {{url}}/register HTTP/1.1
content-type: application/json

{
    "username": "as12312321321d",
    "email": "seaasesea@gmail.com",
    "password": "sea123!!"
}

###

POST  {{url}}/login HTTP/1.1
content-type: application/json

{
    "email": "ismailpvo1535@gmail.com",
    "password": "ismail12"
}

###

###

POST {{url}}/logout HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/user/isAdmin HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/workspace HTTP/1.1
Authorization: Bearer {{token}}

###

# GET {{url}}/workspace/620c29a90858a8f3bdaeafa9 HTTP/1.1
GET {{url}}/workspace/620c29a90858a8f3bdaeafa9 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{url}}/workspace HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "qa"
}

###
PATCH {{url}}/workspace HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "workspace": "6216761f208b1f7460844bfd",
    "name": "iyi senden",
    "participants": [
      "62057173ed9f9a2c1f7449c2",
      "12345653ed9f9a2c1f7449c2",
      "32145679ed9f9a2c1f7449c2",
      "45632156ed9f9a2c1f7449c2"
    ]
}

###
DELETE {{url}}/workspace/621675b41c0d2924707265b1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{url}}/todo/6216761f208b1f7460844bfd HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST {{url}}/todo/6216761f208b1f7460844bfd HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "App will deploy" 
}

###
PATCH {{url}}/todo/6216761f208b1f7460844bfd HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "todo": "6216784eb4084cee233b5941",
    "description": "App will anan",
    "checked": true
}

###

GET {{url}}/admin/dashboard HTTP/1.1
Authorization: Bearer {{token}}